### PR TITLE
Feature/job page

### PR DESCRIPTION
**Pull request by HarunHudaiTan**
Add-Job Update-job sayfaları eklendi login pagede yer almayan signup butonu eklendi

### CODE REVIEW

**Comment by fatih-demirr** [comment]
Harun, the main branch is protected. Please create a new branch named 'develop' and push your commits to the 'develop' branch.

**Comment by fatih-demirr** [comment]
I reviewed your commits, and they are fine. Java 19 is not LTS, but that's okay. If you want to change the URL from localhost to something nicer, like fatihdemir.com, you can update it in the hosts file. Push them to develop branch, and then we can merge.

**Comment by HarunHudaiTan** [comment]
Fatih thank you for reviewing my commits, i will do my best to apply your comments to the project.

**Comment by HarunHudaiTan** [comment]
Fatih i created the 'develop' branch and set the source of the branch as feature/job page it automatically pushed the changes i made in feature/job-page branch to develop branch. What should i do now?  when i try to create a Pull Request it says it is only able to merge when the base is main or master.

**Comment by fatih-demirr** [comment]
That's not a problem. I gave you collaborator permissions, so you can commit without my review. If you want my review, create a new issue in your branch and then push.

**Comment by fatih-demirr** [comment]
keep coding

**Pull request closed without merging**
